### ISSUE TITLE
HTML 4.01 でサポートされているはずのない `<audio>` タグが使われている

### ISSUE THREAD

**Issue by ghost** [yudejp/legacy.yude.jp#3]
@KusaReMKN

**Comment by yude** [comment]
@KusaReMKN

**Comment by KusaReMKN** [comment]
HTML 4.01 なんかに audio が含まれているはずがないし、そもそも bgsound すら非標準なので使えるはずはないのですが、Vodafone では使えたようです[^1]。 ところでケータイ用の HTML は何か別で標準があったはずです。

[^1]: https://www.nslabs.jp/jphone-tags.rhtml

**Comment by KusaReMKN** [comment]
Compact HTML とかいうやつかもしれない

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD Compact HTML 1.0 Draft//EN">
```

**Comment by yude** [comment]
Fixed in edceca7cedd6bd73340c53ee023e3746ca61fdd2
